### ISSUE TITLE
[Feature Request] Display more information

### ISSUE THREAD

**Issue by NovaliX-Dev** [Grayray75/FPS-Display#12]
I really like your mod for it's simple UI, and i was wondering if it was possible to add more information to the screen (like the ping or the memory usage for example). This will be usefull especially for online games, when we need to know the exact ping of the server for example.

Now, i also know this will bring a lot of questions : 
- **How the information should be displayed ? Horizontally or vertically ?**
Based on you're UI, i suggest to implement a horizontal layout first (we can concatenate strings into one we can render after), then we can implement the vertical layout if people request it.

- **What will be the default information to display ?**
FPS, Memory usage and ping is what i think is the best.

- **Is it even possible to get the information i suggested ?**
For the ping we can use the `getLatency` from the `PlayerListEntry` class.
I'm not sure how to get the memory usage of minecraft however. We can use the [Java Runtime API](https://stackoverflow.com/questions/17374743/how-can-i-get-the-memory-that-my-java-program-uses-via-javas-runtime-api), but i'm not sure it's the best way to do it. 

- **What will be the others that can be usefull ?**
For the moment i'm not sure, maybe the number of entities ? We can implement other information if people request them.

Let me know what do you think about this request.

**Comment by Grayray75** [comment]
Thanks for your detailed description of your feature request 😃 
I'm currently rewriting the mod, see [v3](https://github.com/Grayray75/FPS-Display/tree/v3) branch, and intend to display more information, like the average fps and 1% low fps.

But I also want to keep the mod as simple as possible that's why I probably won't add any addition information like memory usage or ping.

Also there already exists a mod called [FPS Monitor](https://modrinth.com/mod/fps-monitor) which seem to show exactly the information you are looking for.

**Comment by NovaliX-Dev** [comment]
Ok so i think we can close this issue for now.

Thanks for the mod suggestion ☺️.
