### ISSUE TITLE
Issue Configuring through in game Mod Menu

### ISSUE THREAD

**Issue by 1x-Kiwi** [Grayray75/FPS-Display#15]
I'm using the mod menu that was recommended on the mod page and when I go in game to configure it I am not able to do anything it just appears as a blurry screen
![image](https://github.com/Grayray75/FPS-Display/assets/134355216/deca572a-1fe5-4aae-b8e8-7a5bae210a9e)

**Comment by jimmydonaldson83** [comment]
hey i found a fix for this set your menu background blur to OFF and then you can read. btw it says please install cloth config api

**Comment by Grayray75** [comment]
Interesting... will have a look at this soon!

Also in order to access the settings menu you need to have: \
[Mod Menu](https://modrinth.com/mod/modmenu) (which just provides a list of installed mods) and 
[YetAnotherConfigLib](https://modrinth.com/mod/yacl) or [Cloth Config API](https://modrinth.com/mod/cloth-config) (a lib for settings menus) installed.
